/**
 * Excel 工具关键词映射
 * 
 * 用于将用户输入的关键词映射到对应的 MCP 工具
 * ⚠️ 注意：所有工具名必须与 MCP Server (office_mcp_server_js) 中的定义一致
 */

export const EXCEL_TOOL_MAPPINGS: Record<string, string[]> = {
  // ==================== 单元格操作 ====================
  '单元格': ['excel_set_cell_value', 'excel_get_cell_value', 'excel_merge_cells'],
  '写入单元格': ['excel_set_cell_value'],
  '读取单元格': ['excel_get_cell_value'],
  '设置单元格': ['excel_set_cell_value'],
  '获取单元格': ['excel_get_cell_value'],
  '取消合并': ['excel_unmerge_cells'],
  '区域': ['excel_set_range_values', 'excel_get_range_values'],
  '范围': ['excel_set_range_values', 'excel_get_range_values'],
  '清空': ['excel_clear_range'],
  '清除': ['excel_clear_range'],
  '清除格式': ['excel_clear_format'],
  '插入单元格': ['excel_insert_cells'],
  '删除单元格': ['excel_delete_cells'],
  'cell': ['excel_set_cell_value', 'excel_get_cell_value'],
  'range': ['excel_set_range_values', 'excel_get_range_values'],
  'merge': ['excel_merge_cells'],
  'unmerge': ['excel_unmerge_cells'],

  // ==================== 成绩统计 ====================
  '成绩': ['excel_set_range_values', 'excel_insert_sum', 'excel_insert_average', 'excel_sort_range'],
  '分数': ['excel_set_cell_value', 'excel_insert_average', 'excel_conditional_format'],
  '平均分': ['excel_insert_average'],
  '总分': ['excel_insert_sum'],
  '求和': ['excel_insert_sum'],
  '平均': ['excel_insert_average'],
  '统计': ['excel_insert_pivot_table', 'excel_insert_count'],
  '排序': ['excel_sort_range'],
  '筛选': ['excel_filter_range'],
  '排名': ['excel_sort_range'],
  'average': ['excel_insert_average'],
  'sum': ['excel_insert_sum'],
  'sort': ['excel_sort_range'],
  'filter': ['excel_filter_range'],

  // ==================== 图表 ====================
  '图表': ['excel_insert_chart', 'excel_set_chart_type', 'excel_format_chart'],
  '柱状图': ['excel_insert_chart'],
  '折线图': ['excel_insert_chart'],
  '饼图': ['excel_insert_chart'],
  '趋势图': ['excel_insert_chart'],
  '可视化': ['excel_insert_chart'],
  '图表标题': ['excel_set_chart_title'],
  '坐标轴标题': ['excel_set_axis_title'],
  '添加系列': ['excel_add_chart_series'],
  '删除图表': ['excel_delete_chart'],
  '移动图表': ['excel_move_chart'],
  '更新图表': ['excel_update_chart'],
  '导出图表': ['excel_export_chart'],
  'chart': ['excel_insert_chart', 'excel_format_chart'],
  'graph': ['excel_insert_chart'],

  // ==================== 公式 ====================
  '公式': ['excel_set_formula', 'excel_insert_sum', 'excel_insert_average', 'excel_insert_if'],
  '获取公式': ['excel_get_formula'],
  '函数': ['excel_set_formula', 'excel_insert_vlookup'],
  'IF': ['excel_insert_if'],
  'VLOOKUP': ['excel_insert_vlookup'],
  'SUM': ['excel_insert_sum'],
  'AVERAGE': ['excel_insert_average'],
  'COUNT': ['excel_insert_count'],
  '条件': ['excel_insert_if', 'excel_conditional_format'],
  'formula': ['excel_set_formula'],

  // ==================== 格式化 ====================
  '格式': ['excel_set_cell_format', 'excel_set_number_format', 'excel_conditional_format'],
  '条件格式': ['excel_conditional_format'],
  '数字格式': ['excel_set_number_format'],
  '日期格式': ['excel_set_date_format'],
  '边框': ['excel_set_border'],
  '填充': ['excel_set_fill_color'],
  '背景色': ['excel_set_fill_color'],
  '字体颜色': ['excel_set_font'],
  '对齐方式': ['excel_set_alignment'],
  '自动换行': ['excel_set_wrap_text'],
  'format': ['excel_set_cell_format'],
  'border': ['excel_set_border'],
  'fill': ['excel_set_fill_color'],
  'alignment': ['excel_set_alignment'],

  // ==================== 工作表管理 ====================
  '工作表': ['excel_add_worksheet', 'excel_rename_worksheet', 'excel_delete_worksheet'],
  '激活工作表': ['excel_activate_worksheet'],
  '获取工作表': ['excel_get_sheet_names'],
  '新建工作表': ['excel_add_worksheet'],
  '添加工作表': ['excel_add_worksheet'],
  '删除工作表': ['excel_delete_worksheet'],
  '重命名工作表': ['excel_rename_worksheet'],
  '复制工作表': ['excel_copy_worksheet'],
  '移动工作表': ['excel_move_worksheet'],
  '隐藏工作表': ['excel_hide_worksheet'],
  '显示工作表': ['excel_unhide_worksheet'],
  'worksheet': ['excel_add_worksheet', 'excel_rename_worksheet'],
  'sheet': ['excel_add_worksheet', 'excel_rename_worksheet'],

  // ==================== 数据分析 ====================
  '数据透视表': ['excel_insert_pivot_table', 'excel_create_pivot_table', 'excel_refresh_pivot_table'],
  '透视表': ['excel_insert_pivot_table', 'excel_create_pivot_table'],
  '创建透视表': ['excel_create_pivot_table'],
  '刷新透视表': ['excel_refresh_pivot_table'],
  '透视表样式': ['excel_set_pivot_table_style'],
  '透视表布局': ['excel_set_pivot_table_layout'],
  '透视层级': ['excel_add_pivot_hierarchy', 'excel_get_pivot_hierarchies'],
  '展开层级': ['excel_expand_pivot_hierarchy'],
  '折叠层级': ['excel_collapse_pivot_hierarchy'],
  '层级项': ['excel_get_pivot_hierarchy_items'],
  '移动层级': ['excel_move_pivot_hierarchy'],
  '删除层级': ['excel_remove_pivot_hierarchy'],
  '层级排序': ['excel_set_pivot_hierarchy_sort'],
  '行字段': ['excel_add_pivot_row_field'],
  '列字段': ['excel_add_pivot_column_field'],
  '数据字段': ['excel_add_pivot_data_field'],
  '筛选字段': ['excel_add_pivot_filter_field'],
  '刷新透视': ['excel_refresh_pivot'],
  '透视表信息': ['excel_get_pivot_table_info'],
  '所有透视表': ['excel_get_all_pivot_tables'],
  '删除透视表': ['excel_delete_pivot_table'],
  '移除透视字段': ['excel_remove_pivot_field'],
  '透视数据': ['excel_pivot_data'],
  '去重': ['excel_remove_duplicates'],
  '删除重复': ['excel_remove_duplicates'],
  '数据验证': ['excel_data_validation', 'excel_add_data_validation'],
  '下拉列表': ['excel_add_data_validation'],
  '获取验证': ['excel_get_data_validation'],
  '删除验证': ['excel_remove_data_validation'],
  '批量验证': ['excel_batch_set_validation'],
  '输入消息': ['excel_set_input_message'],
  '错误提示': ['excel_set_error_alert'],
  '无效单元格': ['excel_get_invalid_cells'],
  '清除无效数据': ['excel_clear_invalid_data'],
  '导入': ['excel_import_csv', 'excel_import_json', 'excel_import_xml'],
  '导出': ['excel_export_csv', 'excel_export_json', 'excel_export_xml'],
  'CSV': ['excel_import_csv', 'excel_export_csv'],
  'JSON': ['excel_import_json', 'excel_export_json'],
  'XML': ['excel_import_xml', 'excel_export_xml'],
  'pivot': ['excel_insert_pivot_table', 'excel_create_pivot_table'],

  // ==================== 切片器 ====================
  '切片器': ['excel_add_slicer', 'excel_get_slicers'],
  '添加切片器': ['excel_add_slicer'],
  '删除切片器': ['excel_delete_slicer'],
  '切片器筛选': ['excel_set_slicer_selection'],
  '清除切片器': ['excel_clear_slicer_selection'],
  '切片器详情': ['excel_get_slicer_detail'],
  '切片器项': ['excel_get_slicer_items'],
  '更新切片器': ['excel_update_slicer'],
  'slicer': ['excel_add_slicer', 'excel_get_slicers'],

  // ==================== 表格增强 ====================
  '表格': ['excel_create_table_enhanced', 'excel_get_table_info'],
  '创建表格': ['excel_create_table_enhanced'],
  '表格样式': ['excel_set_table_style'],
  '添加表格行': ['excel_add_table_row'],
  '添加表格列': ['excel_add_table_column'],
  '删除表格行': ['excel_delete_table_row'],
  '删除表格列': ['excel_delete_table_column'],
  '表格数据': ['excel_get_table_data'],
  '清除表格筛选': ['excel_clear_table_filter'],
  '表格转区域': ['excel_convert_table_to_range'],
  'table': ['excel_create_table_enhanced', 'excel_get_table_info'],

  // ==================== 批注操作 ====================
  '批注': ['excel_add_comment', 'excel_get_comments', 'excel_delete_comment'],
  '添加批注': ['excel_add_comment'],
  '获取批注': ['excel_get_comments'],
  '删除批注': ['excel_delete_comment'],
  '编辑批注': ['excel_edit_comment'],
  '回复批注': ['excel_reply_comment'],
  '解决批注': ['excel_resolve_comment'],
  '批注详情': ['excel_get_comment_detail'],
  '单元格批注': ['excel_get_cell_comment'],
  'comment': ['excel_add_comment', 'excel_get_comments'],

  // ==================== 图片操作 ====================
  '图片': ['excel_insert_image', 'excel_get_images'],
  '插入图片': ['excel_insert_image'],
  '删除图片': ['excel_delete_image'],
  '移动图片': ['excel_move_image'],
  '调整图片': ['excel_resize_image'],
  '图片属性': ['excel_set_image_properties'],
  'image': ['excel_insert_image', 'excel_get_images'],

  // ==================== 形状操作 ====================
  '形状': ['excel_add_shape', 'excel_get_shapes'],
  '插入形状': ['excel_add_shape'],
  '删除形状': ['excel_delete_shape'],
  '形状文本': ['excel_add_shape_text'],
  '形状填充': ['excel_set_shape_fill'],
  '形状边框': ['excel_set_shape_line'],
  '形状详情': ['excel_get_shape_detail'],
  '更新形状': ['excel_update_shape'],
  'shape': ['excel_add_shape', 'excel_get_shapes'],

  // ==================== 条件格式扩展 ====================
  '色阶': ['excel_add_color_scale_format'],
  '数据条': ['excel_add_data_bar_format'],
  '图标集': ['excel_add_icon_set_format'],
  '单元格值': ['excel_add_cell_value_format'],
  '包含文本': ['excel_add_text_contains_format'],
  '前N项': ['excel_add_top_bottom_format'],
  '清除条件格式': ['excel_clear_conditional_formats'],
  '获取条件格式': ['excel_get_conditional_formats'],
  '删除条件格式': ['excel_delete_conditional_format'],
  'color scale': ['excel_add_color_scale_format'],
  'data bar': ['excel_add_data_bar_format'],
  'icon set': ['excel_add_icon_set_format'],

  // ==================== 统计分析 ====================
  '相关性': ['excel_correlation'],
  '回归': ['excel_regression'],
  'T检验': ['excel_t_test'],
  't检验': ['excel_t_test'],
  '直方图': ['excel_histogram'],
  '预测': ['excel_forecast'],
  '生成排名': ['excel_generate_ranking'],
  'correlation': ['excel_correlation'],
  'regression': ['excel_regression'],
  'histogram': ['excel_histogram'],
  'forecast': ['excel_forecast'],

  // ==================== 教育工具 ====================
  '班级统计': ['excel_class_stats'],
  '成绩统计': ['excel_class_stats'],
  '考勤统计': ['excel_attendance_stats'],
  '考勤': ['excel_attendance_stats'],
  'class stats': ['excel_class_stats'],
  'attendance': ['excel_attendance_stats'],

  // ==================== 其他操作 ====================
  '冻结': ['excel_freeze_panes'],
  '冻结窗格': ['excel_freeze_panes'],
  '自动列宽': ['excel_autofit_columns'],
  '列宽': ['excel_set_column_width'],
  '行高': ['excel_set_row_height'],
  '隐藏列': ['excel_hide_columns'],
  '显示列': ['excel_unhide_columns'],
  '保护工作表': ['excel_protect_sheet'],
  '取消保护': ['excel_unprotect_sheet'],
  '保护工作簿': ['excel_protect_workbook'],
  '复制': ['excel_copy_range'],
  '复制格式': ['excel_copy_format'],
  '剪切': ['excel_cut_range'],
  '粘贴': ['excel_paste_range'],
  '查找': ['excel_find_cell'],
  '替换': ['excel_replace_cell'],
  '定义名称': ['excel_define_name'],
  '刷新数据': ['excel_refresh_data'],
  '连接数据库': ['excel_connect_database'],
  '数组公式': ['excel_array_formula'],
  '计算': ['excel_calculate'],
  '分组': ['excel_group_data'],
  'freeze': ['excel_freeze_panes'],
  'copy': ['excel_copy_range'],
  'cut': ['excel_cut_range'],
  'paste': ['excel_paste_range'],
  'find': ['excel_find_cell'],
  'replace': ['excel_replace_cell'],
  'protect': ['excel_protect_sheet']
}
