/**
 * Word 工具关键词映射
 * 
 * 用于将用户输入的关键词映射到对应的 MCP 工具
 * ⚠️ 注意：所有工具名必须与 MCP Server (office_mcp_server_js) 中的定义一致
 */

export const WORD_TOOL_MAPPINGS: Record<string, string[]> = {
  // ==================== 图片相关 ====================
  '图片': ['word_insert_image', 'word_resize_image', 'word_move_image'],
  '图': ['word_insert_image', 'word_resize_image', 'word_move_image'],
  '照片': ['word_insert_image', 'word_resize_image'],
  'image': ['word_insert_image', 'word_resize_image', 'word_move_image'],
  'picture': ['word_insert_image', 'word_resize_image', 'word_move_image'],
  'photo': ['word_insert_image', 'word_resize_image'],
  '添加图片': ['word_insert_image'],
  '图片占位符': ['word_insert_image'],
  '占位符': ['word_insert_image'],
  'placeholder': ['word_insert_image'],
  'insert image': ['word_insert_image'],
  'add image': ['word_insert_image'],
  '调整图片大小': ['word_resize_image'],
  '旋转图片': ['word_rotate_image'],
  '删除图片': ['word_delete_image'],
  '替换图片': ['word_replace_image'],
  '获取图片': ['word_get_images'],
  '图片列表': ['word_get_images'],
  '图片标题': ['word_add_image_caption'],
  '压缩图片': ['word_compress_images'],
  // 图片尺寸相关关键词
  '宽度': ['word_resize_image'],
  '高度': ['word_resize_image'],
  '尺寸': ['word_resize_image'],
  '厘米': ['word_resize_image'],
  'cm': ['word_resize_image'],
  '英寸': ['word_resize_image'],
  'inch': ['word_resize_image'],
  '像素': ['word_resize_image'],
  'px': ['word_resize_image'],
  '设为': ['word_resize_image', 'word_set_font_size', 'word_set_font_color'],
  '改为': ['word_resize_image', 'word_replace_text'],
  'resize': ['word_resize_image'],
  'width': ['word_resize_image'],
  'height': ['word_resize_image'],
  'size image': ['word_resize_image'],
  '缩小图片': ['word_resize_image'],
  '放大图片': ['word_resize_image'],
  '图片大小': ['word_resize_image'],
  '图片尺寸': ['word_resize_image'],
  '图片宽度': ['word_resize_image'],
  '图片高度': ['word_resize_image'],
  // ==================== 图表相关 ====================
  '图表': ['word_insert_chart', 'word_get_charts'],
  'chart': ['word_insert_chart', 'word_get_charts'],
  '柱状图': ['word_insert_chart'],
  '条形图': ['word_insert_chart'],
  '折线图': ['word_insert_chart'],
  '饼图': ['word_insert_chart'],
  '饼状图': ['word_insert_chart'],
  '面积图': ['word_insert_chart'],
  '散点图': ['word_insert_chart'],
  '环形图': ['word_insert_chart'],
  '数据图': ['word_insert_chart'],
  '统计图': ['word_insert_chart'],
  '插入图表': ['word_insert_chart'],
  '创建图表': ['word_insert_chart'],
  '添加图表': ['word_insert_chart'],
  '生成图表': ['word_insert_chart'],
  'bar chart': ['word_insert_chart'],
  'column chart': ['word_insert_chart'],
  'line chart': ['word_insert_chart'],
  'pie chart': ['word_insert_chart'],
  'area chart': ['word_insert_chart'],
  'scatter chart': ['word_insert_chart'],
  'insert chart': ['word_insert_chart'],
  'create chart': ['word_insert_chart'],

  // 文字环绕相关关键词
  '环绕': ['word_wrap_text_around_image', 'word_set_image_position'],
  '文字环绕': ['word_wrap_text_around_image'],
  '四周型': ['word_wrap_text_around_image'],
  '四周型环绕': ['word_wrap_text_around_image'],
  '紧密型': ['word_wrap_text_around_image'],
  '紧密型环绕': ['word_wrap_text_around_image'],
  '穿越型': ['word_wrap_text_around_image'],
  '穿越型环绕': ['word_wrap_text_around_image'],
  '上下型': ['word_wrap_text_around_image'],
  '上下型环绕': ['word_wrap_text_around_image'],
  '衬于文字下方': ['word_wrap_text_around_image'],
  '浮于文字上方': ['word_wrap_text_around_image'],
  '嵌入型': ['word_set_image_position'],
  'wrap': ['word_wrap_text_around_image'],
  'square': ['word_wrap_text_around_image'],
  'tight': ['word_wrap_text_around_image'],
  'behind text': ['word_wrap_text_around_image'],
  'in front': ['word_wrap_text_around_image'],

  // ==================== 对齐相关 ====================
  '居中': ['word_set_paragraph_alignment'],
  '左对齐': ['word_set_paragraph_alignment'],
  '右对齐': ['word_set_paragraph_alignment'],
  'center': ['word_set_paragraph_alignment'],
  'align': ['word_set_paragraph_alignment'],

  // ==================== 超链接相关 ====================
  '超链接': ['word_insert_hyperlink', 'word_remove_hyperlink'],
  '链接': ['word_insert_hyperlink', 'word_remove_hyperlink'],
  'hyperlink': ['word_insert_hyperlink', 'word_remove_hyperlink'],
  'link': ['word_insert_hyperlink', 'word_remove_hyperlink'],
  '添加链接': ['word_insert_hyperlink'],
  '插入链接': ['word_insert_hyperlink'],
  '添加超链接': ['word_insert_hyperlink'],
  '插入超链接': ['word_insert_hyperlink'],
  '删除链接': ['word_remove_hyperlink'],
  '删除超链接': ['word_remove_hyperlink'],
  '移除链接': ['word_remove_hyperlink'],

  // ==================== 字体格式化 ====================
  '字体': ['word_set_font', 'word_set_font_size', 'word_set_font_color'],
  '颜色': ['word_set_font_color'],
  '字体颜色': ['word_set_font_color'],
  '文字颜色': ['word_set_font_color'],
  // 具体颜色名称
  '红色': ['word_set_font_color'],
  '蓝色': ['word_set_font_color'],
  '绿色': ['word_set_font_color'],
  '黑色': ['word_set_font_color'],
  '白色': ['word_set_font_color'],
  '黄色': ['word_set_font_color'],
  '橙色': ['word_set_font_color'],
  '紫色': ['word_set_font_color'],
  '灰色': ['word_set_font_color'],
  '粉色': ['word_set_font_color'],
  'red': ['word_set_font_color'],
  'blue': ['word_set_font_color'],
  'green': ['word_set_font_color'],
  '加粗': ['word_set_bold'],
  '粗体': ['word_set_bold'],
  '斜体': ['word_set_italic'],
  '下划线': ['word_set_underline'],
  '字号': ['word_set_font_size'],
  '大小': ['word_set_font_size'],
  '字体名称': ['word_set_font_name'],
  '宋体': ['word_set_font_name'],
  '黑体': ['word_set_font_name'],
  '楷体': ['word_set_font_name'],
  '微软雅黑': ['word_set_font_name'],
  'font': ['word_set_font', 'word_set_font_size', 'word_set_font_color'],
  'color': ['word_set_font_color'],
  'bold': ['word_set_bold'],
  'italic': ['word_set_italic'],
  'underline': ['word_set_underline'],
  '高亮': ['word_set_highlight'],
  '删除线': ['word_set_strikethrough'],
  '上标': ['word_set_superscript'],
  '下标': ['word_set_subscript'],

  // ==================== 段落格式化 ====================
  '段落': ['word_add_paragraph', 'word_set_paragraph_alignment', 'word_set_paragraph_spacing'],
  '第一段': ['word_set_font_color', 'word_set_bold', 'word_set_font_size'],
  '第二段': ['word_set_font_color', 'word_set_bold', 'word_set_font_size'],
  '第三段': ['word_set_font_color', 'word_set_bold', 'word_set_font_size'],
  '段': ['word_set_font_color', 'word_set_bold', 'word_set_font_size'],
  '缩进': ['word_set_paragraph_indent'],
  '行距': ['word_set_line_spacing'],
  '首行缩进': ['word_set_paragraph_indent'],
  '间距': ['word_set_paragraph_spacing'],
  'paragraph': ['word_add_paragraph', 'word_set_paragraph_alignment'],
  'indent': ['word_set_paragraph_indent'],
  'spacing': ['word_set_paragraph_spacing', 'word_set_line_spacing'],

  // ==================== 文本插入 ====================
  '添加': ['word_insert_text', 'word_add_paragraph'],
  '插入': ['word_insert_text', 'word_insert_table', 'word_insert_image', 'word_insert_chart'],
  '插入文本': ['word_insert_text'],
  '添加文本': ['word_insert_text'],
  '添加内容': ['word_insert_text'],
  '插入内容': ['word_insert_text'],
  '写入': ['word_insert_text', 'word_set_cell_value'],
  '输入': ['word_insert_text'],
  '模版': ['word_insert_text'],
  '模板': ['word_insert_text'],
  '介绍': ['word_insert_text'],
  '简历': ['word_insert_text'],
  'insert': ['word_insert_text', 'word_insert_table', 'word_insert_image'],
  'insert text': ['word_insert_text'],
  'add text': ['word_insert_text'],
  'add content': ['word_insert_text'],
  'write': ['word_insert_text'],
  'template': ['word_insert_text'],

  // ==================== 查找替换 ====================
  '替换': ['word_replace_text'],
  '改成': ['word_replace_text'],
  '修改': ['word_replace_text'],
  'find': ['word_search_text'],
  'replace': ['word_replace_text'],
  'search': ['word_search_text'],

  // ==================== 目录生成 ====================
  '目录': ['word_insert_toc', 'word_update_toc'],
  'TOC': ['word_insert_toc', 'word_update_toc'],
  'table of contents': ['word_insert_toc'],
  '更新目录': ['word_update_toc'],

  // ==================== 格式刷 ====================
  '格式刷': ['word_copy_format'],
  '复制格式': ['word_copy_format'],
  '应用格式': ['word_copy_format'],
  'format painter': ['word_copy_format'],
  'copy format': ['word_copy_format'],

  // ==================== 样式应用 ====================
  '样式': ['word_apply_style', 'word_create_style'],
  '标题': ['word_set_heading', 'word_apply_style'],
  '标题1': ['word_set_heading'],
  '标题2': ['word_set_heading'],
  '标题3': ['word_set_heading'],
  '一级标题': ['word_set_heading'],
  '二级标题': ['word_set_heading'],
  '三级标题': ['word_set_heading'],
  '四级标题': ['word_set_heading'],
  '五级标题': ['word_set_heading'],
  '六级标题': ['word_set_heading'],
  'heading1': ['word_set_heading'],
  'heading2': ['word_set_heading'],
  'heading3': ['word_set_heading'],
  'h1': ['word_set_heading'],
  'h2': ['word_set_heading'],
  'h3': ['word_set_heading'],
  'style': ['word_apply_style', 'word_create_style'],
  'heading': ['word_set_heading'],
  '重置样式': ['word_reset_style'],

  // ==================== 列表 ====================
  '列表': ['word_apply_list_style'],
  '有序列表': ['word_apply_list_style'],
  '无序列表': ['word_apply_list_style'],
  '编号': ['word_apply_list_style'],
  '项目符号': ['word_apply_list_style'],
  'list': ['word_apply_list_style'],
  'bullet': ['word_apply_list_style'],
  'numbered': ['word_apply_list_style'],

  // ==================== 表格 ====================
  '表格': ['word_insert_table', 'word_set_table_style', 'word_format_table', 'word_set_cell_value'],
  '插入表格': ['word_insert_table'],
  '创建表格': ['word_insert_table'],
  'table': ['word_insert_table', 'word_set_table_style', 'word_set_cell_value'],
  'insert table': ['word_insert_table'],
  'x': ['word_insert_table'], // Support "4x3"
  '*': ['word_insert_table'], // Support "4*3"
  '删除表格': ['word_delete_table'],
  // 行操作
  '添加行': ['word_add_row'],
  '插入行': ['word_add_row'],
  '新增行': ['word_add_row'],
  '增加行': ['word_add_row'],
  '加一行': ['word_add_row'],
  '添加一行': ['word_add_row'],
  '最后添加': ['word_add_row'],
  '末尾添加': ['word_add_row'],
  'add row': ['word_add_row'],
  'insert row': ['word_add_row'],
  '删除行': ['word_delete_row'],
  '删除一行': ['word_delete_row'],
  'delete row': ['word_delete_row'],
  // 列操作
  '添加列': ['word_add_column'],
  '插入列': ['word_add_column'],
  '新增列': ['word_add_column'],
  '增加列': ['word_add_column'],
  '加一列': ['word_add_column'],
  '添加一列': ['word_add_column'],
  'add column': ['word_add_column'],
  'insert column': ['word_add_column'],
  '删除列': ['word_delete_column'],
  '删除一列': ['word_delete_column'],
  'delete column': ['word_delete_column'],
  'remove column': ['word_delete_column'],
  '拆分单元格': ['word_split_cell'],
  // 单元格操作
  '合并单元格': ['word_merge_cells'],
  '合并': ['word_merge_cells', 'word_merge_paragraphs'],
  'merge cells': ['word_merge_cells'],
  'merge': ['word_merge_cells'],
  '单元格': ['word_set_cell_value', 'word_get_cell_value', 'word_merge_cells'],
  '写入单元格': ['word_set_cell_value'],
  '填入': ['word_set_cell_value'],
  '填充': ['word_set_cell_value'],
  '设置单元格': ['word_set_cell_value'],
  '表格内容': ['word_set_cell_value', 'word_get_cell_value'],
  '行第': ['word_set_cell_value'],
  '列写': ['word_set_cell_value'],
  'cell': ['word_set_cell_value', 'word_get_cell_value'],
  'set cell': ['word_set_cell_value'],
  'cell value': ['word_set_cell_value', 'word_get_cell_value'],

  // ==================== 页面设置 ====================
  '页边距': ['word_set_page_margins', 'word_get_page_margins'],
  '边距': ['word_set_page_margins', 'word_get_page_margins'],
  '上边距': ['word_set_page_margins'],
  '下边距': ['word_set_page_margins'],
  '左边距': ['word_set_page_margins'],
  '右边距': ['word_set_page_margins'],
  'margin': ['word_set_page_margins', 'word_get_page_margins'],
  'margins': ['word_set_page_margins', 'word_get_page_margins'],
  'page margin': ['word_set_page_margins'],
  '页面方向': ['word_set_page_orientation', 'word_get_page_orientation'],
  '纸张方向': ['word_set_page_orientation'],
  '横向': ['word_set_page_orientation'],
  '纵向': ['word_set_page_orientation'],
  'orientation': ['word_set_page_orientation'],
  'landscape': ['word_set_page_orientation'],
  'portrait': ['word_set_page_orientation'],
  '页面大小': ['word_set_page_size', 'word_get_page_size'],
  '纸张大小': ['word_set_page_size'],
  'A4': ['word_set_page_size'],
  'A3': ['word_set_page_size'],
  'page size': ['word_set_page_size'],
  '分页': ['word_insert_page_break'],
  '分节': ['word_insert_section_break'],
  'page break': ['word_insert_page_break'],
  'section break': ['word_insert_section_break'],

  // ==================== 引用和注释 ====================
  '脚注': ['word_insert_footnote'],
  '尾注': ['word_insert_endnote'],
  '交叉引用': ['word_insert_cross_reference'],
  '引文': ['word_insert_citation'],
  '参考文献': ['word_insert_bibliography'],
  'footnote': ['word_insert_footnote'],
  'endnote': ['word_insert_endnote'],
  'citation': ['word_insert_citation'],
  'bibliography': ['word_insert_bibliography'],

  // ==================== 页眉页脚 ====================
  '页眉': ['word_insert_header', 'word_get_header', 'word_clear_header'],
  '页脚': ['word_insert_footer', 'word_get_footer', 'word_clear_footer'],
  '添加页眉': ['word_insert_header'],
  '添加页脚': ['word_insert_footer'],
  '清除页眉': ['word_clear_header'],
  '清除页脚': ['word_clear_footer'],
  '获取页眉': ['word_get_header'],
  '获取页脚': ['word_get_footer'],
  'header': ['word_insert_header', 'word_get_header', 'word_clear_header'],
  'footer': ['word_insert_footer', 'word_get_footer', 'word_clear_footer'],

  // ==================== 书签操作 ====================
  '书签': ['word_create_bookmark', 'word_insert_bookmark', 'word_get_bookmarks', 'word_goto_bookmark'],
  '创建书签': ['word_create_bookmark'],
  '删除书签': ['word_delete_bookmark'],
  '获取书签': ['word_get_bookmarks'],
  '跳转书签': ['word_goto_bookmark'],
  '更新书签': ['word_update_bookmark'],
  '检查书签': ['word_check_bookmark'],
  'bookmark': ['word_create_bookmark', 'word_insert_bookmark', 'word_get_bookmarks'],

  // ==================== 批注操作 ====================
  '批注': ['word_add_comment', 'word_get_comments', 'word_delete_comment'],
  '注释': ['word_add_comment', 'word_get_comments'],
  '添加批注': ['word_add_comment'],
  '获取批注': ['word_get_comments'],
  '批注详情': ['word_get_comment_detail'],
  '删除批注': ['word_delete_comment'],
  '回复批注': ['word_reply_comment'],
  '解决批注': ['word_resolve_comment'],
  '评论': ['word_add_comment', 'word_get_comments'],
  'comment': ['word_add_comment', 'word_get_comments', 'word_delete_comment'],

  // ==================== 修订跟踪 ====================
  '修订': ['word_enable_track_changes', 'word_get_track_changes', 'word_accept_track_change'],
  '修订跟踪': ['word_enable_track_changes', 'word_disable_track_changes', 'word_get_track_changes_status'],
  '启用修订': ['word_enable_track_changes'],
  '禁用修订': ['word_disable_track_changes'],
  '关闭修订': ['word_disable_track_changes'],
  '接受修订': ['word_accept_track_change', 'word_accept_all_track_changes'],
  '拒绝修订': ['word_reject_track_change', 'word_reject_all_track_changes'],
  '接受所有修订': ['word_accept_all_track_changes'],
  '拒绝所有修订': ['word_reject_all_track_changes'],
  '获取修订': ['word_get_track_changes'],
  'track changes': ['word_enable_track_changes', 'word_get_track_changes'],
  'revision': ['word_enable_track_changes', 'word_get_track_changes'],

  // ==================== 域操作 ====================
  '域': ['word_insert_field', 'word_get_fields', 'word_update_field'],
  '字段': ['word_insert_field', 'word_get_fields'],
  '插入域': ['word_insert_field'],
  '更新域': ['word_update_field', 'word_update_all_fields'],
  '更新所有域': ['word_update_all_fields'],
  '删除域': ['word_delete_field'],
  '锁定域': ['word_lock_field'],
  '解锁域': ['word_unlock_field'],
  '域结果': ['word_get_field_result'],
  'field': ['word_insert_field', 'word_get_fields', 'word_update_field'],

  // ==================== 内容控件 ====================
  '内容控件': ['word_insert_content_control', 'word_get_content_controls'],
  '控件': ['word_insert_content_control', 'word_get_content_controls'],
  '插入控件': ['word_insert_content_control'],
  '删除控件': ['word_delete_content_control'],
  '清除控件': ['word_clear_content_control'],
  '设置控件值': ['word_set_content_control_value'],
  '获取控件值': ['word_get_content_control_value'],
  'content control': ['word_insert_content_control', 'word_get_content_controls'],

  // ==================== 文档操作 ====================
  '保存': ['word_save_document'],
  '保存文档': ['word_save_document'],
  '另存为': ['word_save_as_document'],
  '关闭文档': ['word_close_document'],
  '打开文档': ['word_open_document'],
  '打印': ['word_print_document'],
  '打印文档': ['word_print_document'],
  '打印预览': ['word_print_preview'],
  '文档属性': ['word_get_document_properties', 'word_set_document_properties'],
  '文档统计': ['word_get_document_statistics'],
  '字数统计': ['word_get_document_statistics'],
  '字数': ['word_get_document_statistics'],
  '文档路径': ['word_get_document_path'],
  '保存状态': ['word_get_save_status'],
  '关闭预览': ['word_close_print_preview'],
  'save': ['word_save_document'],
  'save as': ['word_save_as_document'],
  'print': ['word_print_document'],
  'close': ['word_close_document'],
  'open': ['word_open_document'],
  'document properties': ['word_get_document_properties'],
  'statistics': ['word_get_document_statistics'],

  // ==================== 形状操作 ====================
  '形状': ['word_insert_shape', 'word_delete_shape', 'word_get_shape'],
  '插入形状': ['word_insert_shape'],
  '删除形状': ['word_delete_shape'],
  '移动形状': ['word_move_shape'],
  '调整形状': ['word_resize_shape'],
  '形状填充': ['word_set_shape_fill'],
  '形状边框': ['word_set_shape_line'],
  '形状属性': ['word_set_shape_properties'],
  '矩形': ['word_insert_shape'],
  '圆形': ['word_insert_shape'],
  '箭头': ['word_insert_shape'],
  'shape': ['word_insert_shape', 'word_delete_shape', 'word_get_shape'],
  'rectangle': ['word_insert_shape'],
  'circle': ['word_insert_shape'],
  'arrow': ['word_insert_shape'],

  // ==================== 画布操作 ====================
  '画布': ['word_insert_canvas', 'word_get_canvases', 'word_delete_canvas'],
  '绘图画布': ['word_insert_canvas'],
  '插入画布': ['word_insert_canvas'],
  '删除画布': ['word_delete_canvas'],
  '几何形状': ['word_insert_geometric_shape'],
  '画布形状': ['word_get_canvas_shapes', 'word_add_shape_to_canvas'],
  'canvas': ['word_insert_canvas', 'word_get_canvases'],

  // ==================== 协作操作 ====================
  '协作': ['word_get_coauthoring_status', 'word_get_coauthors'],
  '共同编辑': ['word_get_coauthoring_status'],
  '协作者': ['word_get_coauthors'],
  '协作状态': ['word_get_coauthoring_status'],
  '协作锁': ['word_get_coauthoring_locks'],
  '锁定': ['word_request_coauthoring_lock', 'word_lock_field'],
  '解锁': ['word_release_coauthoring_lock', 'word_unlock_field'],
  '同步': ['word_sync_coauthoring_changes'],
  'coauthor': ['word_get_coauthoring_status', 'word_get_coauthors'],
  'collaboration': ['word_get_coauthoring_status'],

  // ==================== 冲突处理 ====================
  '冲突': ['word_get_conflicts', 'word_merge_conflict'],
  '获取冲突': ['word_get_conflicts'],
  '接受本地': ['word_accept_local_version'],
  '接受服务器': ['word_accept_server_version'],
  '合并冲突': ['word_merge_conflict'],
  '冲突详情': ['word_get_conflict_detail'],
  '接受所有本地': ['word_accept_all_local_versions'],
  '接受所有服务器': ['word_accept_all_server_versions'],
  'conflict': ['word_get_conflicts', 'word_merge_conflict'],

  // ==================== 墨迹注释 ====================
  '墨迹': ['word_add_ink_annotation', 'word_get_ink_annotations'],
  '手写': ['word_add_ink_annotation'],
  '墨迹注释': ['word_add_ink_annotation', 'word_get_ink_annotations'],
  '删除墨迹': ['word_delete_ink_annotation', 'word_delete_all_ink_annotations'],
  '墨迹详情': ['word_get_ink_annotation_detail'],
  'ink': ['word_add_ink_annotation', 'word_get_ink_annotations'],

  // ==================== 教育工具 ====================
  '邮件合并': ['word_mail_merge'],
  '试卷': ['word_exam_header', 'word_question_section'],
  '试卷头': ['word_exam_header'],
  '考试': ['word_exam_header'],
  '题目': ['word_question_section'],
  '教案': ['word_lesson_plan'],
  '课程计划': ['word_lesson_plan'],
  '公文': ['word_official_header'],
  '公文头': ['word_official_header'],
  '红头文件': ['word_official_header'],
  'mail merge': ['word_mail_merge'],
  'exam': ['word_exam_header'],
  'lesson plan': ['word_lesson_plan'],

  // ==================== 其他文本操作 ====================
  '读取文档': ['word_read_document'],
  '获取段落': ['word_get_paragraphs'],
  '获取选中': ['word_get_selected_text'],
  '选中文本': ['word_get_selected_text'],
  '清除格式': ['word_clear_formatting'],
  '复制': ['word_copy_text'],
  '剪切': ['word_cut_text'],
  '粘贴': ['word_paste_text'],
  '删除文本': ['word_delete_text'],
  '删除段落': ['word_delete_paragraph'],
  '移动段落': ['word_move_paragraph'],
  '拆分段落': ['word_split_paragraph'],
  '指定位置插入段落': ['word_insert_paragraph_at'],
  '格式化文本': ['word_format_text'],
  '选择文本': ['word_select_text_range'],
  '选中范围': ['word_select_text_range'],
  '表格转文本': ['word_table_to_text'],
  '单元格边框': ['word_set_cell_border'],
  '单元格底纹': ['word_set_cell_shading'],
  '主题': ['word_apply_theme'],
  '背景色': ['word_set_background_color'],
  '获取样式': ['word_list_styles'],
  'copy': ['word_copy_text'],
  'cut': ['word_cut_text'],
  'paste': ['word_paste_text'],
  'delete': ['word_delete_text', 'word_delete_paragraph'],
  'theme': ['word_apply_theme']
}
